# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 install! 'cocoapods', :deterministic_uuids => false

target 'soqqle' do
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'Mixpanel'
  # Pods for soqqle
    rn_maps_path = '../node_modules/react-native-maps'
      inherit! :search_paths
      pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge', # Include this for RN >= 0.47
        'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
        'cxxreact',
        'RCTAnimation', # Needed for FlatList and animations running on native UI thread
        'RCTBlob',
        #'RCTPushNotification', # Needed if using push notification
        'RCTActionSheet', # Needed for specific use cases
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket', # Needed for debugging
        # Add any other subspecs you want to use in your project
        ]
        # Explicitly include Yoga if you are using RN >= 0.42.0
        pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

        # Third party deps podspec link
        pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
        pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
        pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

        

        pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

      pod 'react-native-video', :path => '../node_modules/react-native-video'
      pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
      pod 'Bolts'
      pod 'FBSDKCoreKit', '4.40.0'
      pod 'FBSDKLoginKit', '4.40.0'
      pod 'FBSDKShareKit', '4.40.0'


    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'
 # pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'
 #pod 'AccountKit'



  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


  

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
